### ISSUE TITLE
Run MiguruWM without explorer.exe

### ISSUE THREAD

**Issue by kyx0r** [imawizard/MiguruWM#22]
Hi wizard,

Thanks for fixing all the issues this far. My question if it is possible to run MiguruWM without explorer?
It crashes and nothing works once explorer.exe is killed. How difficult would it be (if possible at all) to keep it functioning in such
an environment?

**Comment by imawizard** [comment]
np, thanks for the reports.

Do you still want to use multiple workspaces/desktops or do you just want to tile the windows of a single one?
Because without explorer.exe the virtual desktops can't be used and there's no Immersive Shell COM object (at least for Win10). You could make the usage of `this.VD` in the code conditional so no errors would be thrown if there's no explorer.exe, but then not much functionality would be left.

For such a use case window managers like komorebi that don't utilize native virtual desktops would be better suited.

**Comment by kyx0r** [comment]
Ahh, I see. I think its alright. I just hide the taskbar and it seems to be good enough. Thanks for such wonderful project!
